Console.WriteLine("=== Atc.SourceGenerators Sample ===\n");

// Create service collection
var services = new ServiceCollection();

// Register all services decorated with [Registration] attribute from both assemblies
// These extension methods are generated by the source generator
services.AddDependencyRegistrationsFromDependencyRegistration();
services.AddDependencyRegistrationsFromDomain();

// Build service provider
var serviceProvider = services.BuildServiceProvider();

Console.WriteLine("1. Testing Scoped Service (IUserService -> UserService):");
using (var scope = serviceProvider.CreateScope())
{
    var userService = scope.ServiceProvider.GetRequiredService<IUserService>();
    userService.CreateUser("John Doe");
    userService.DeleteUser("Jane Smith");
}

Console.WriteLine("\n2. Testing Singleton Service (CacheService):");
var cache1 = serviceProvider.GetRequiredService<CacheService>();
var cache2 = serviceProvider.GetRequiredService<CacheService>();
cache1.Set("key1", "value1");
cache2.Set("key2", "value2");
Console.WriteLine($"Same instance: {ReferenceEquals(cache1, cache2)}");

Console.WriteLine("\n3. Testing Transient Service (LoggerService):");
var logger1 = serviceProvider.GetRequiredService<LoggerService>();
var logger2 = serviceProvider.GetRequiredService<LoggerService>();
logger1.Log("Message from logger 1");
logger2.Log("Message from logger 2");
Console.WriteLine($"Different instances: {!ReferenceEquals(logger1, logger2)}");

Console.WriteLine("\n4. Testing Service with AsSelf (EmailNotificationService):");

// Can be resolved as interface
var notificationService = serviceProvider.GetRequiredService<INotificationService>();
notificationService.Send("Hello via interface!");

// Can also be resolved as concrete type
var emailService = serviceProvider.GetRequiredService<EmailNotificationService>();
emailService.SendBulk(["Email 1", "Email 2", "Email 3"]);

Console.WriteLine($"\nSame instance: {ReferenceEquals(notificationService, emailService)}");

Console.WriteLine("\n=== All tests completed successfully! ===");