// ReSharper disable StringLiteralTypo
Console.WriteLine("=== Atc.SourceGenerators - Options Binding Sample ===\n");

// Build configuration
var configuration = new ConfigurationBuilder()
    .SetBasePath(Directory.GetCurrentDirectory())
    .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
    .Build();

// Create service collection
var services = new ServiceCollection();

// Register all options decorated with [OptionsBinding] attribute from both assemblies
// These extension methods are generated by the source generator
services.AddOptionsFromOptionsBinding(configuration);
services.AddOptionsFromDomain(configuration);

Console.WriteLine("=== Demonstrating Early Access to Options (No BuildServiceProvider!) ===\n");
Console.WriteLine("Early access allows retrieving bound and validated options DURING service registration");
Console.WriteLine("This avoids the anti-pattern of calling BuildServiceProvider() mid-registration.\n");

// Approach 1: Using GetOrAdd{OptionsName}From{Assembly}() methods
Console.WriteLine("1. Using GetOrAdd methods (Approach 1):");
var dbEarly = services.GetOrAddDatabaseOptionsFromOptionsBinding(configuration);
Console.WriteLine($"   ✓ Retrieved DatabaseOptions early: ConnectionString={dbEarly.ConnectionString[..Math.Min(30, dbEarly.ConnectionString.Length)]}...");
Console.WriteLine($"   ✓ MaxRetries: {dbEarly.MaxRetries}");

// Call again to demonstrate idempotency
var dbEarly2 = services.GetOrAddDatabaseOptionsFromOptionsBinding(configuration);
Console.WriteLine($"   ✓ Called again (idempotent): Same instance? {ReferenceEquals(dbEarly, dbEarly2)}");

// Approach 2: GetOrAdd methods are idempotent - calling again retrieves from cache
Console.WriteLine("\n2. Retrieving other options via GetOrAdd (Approach 2):");
var apiEarly = services.GetOrAddApiOptionsFromOptionsBinding(configuration);
Console.WriteLine($"   ✓ Retrieved ApiOptions: BaseUrl={apiEarly.BaseUrl}");

var loggingEarly = services.GetOrAddLoggingOptionsFromOptionsBinding(configuration);
Console.WriteLine($"   ✓ Retrieved LoggingOptions: Level={loggingEarly.Level}");

// Use case: Conditional service registration based on configuration
Console.WriteLine("\n3. Conditional Service Registration (Common Use Case):");
Console.WriteLine("   Using early-access options to decide which services to register...");

if (loggingEarly.EnableFile && !string.IsNullOrWhiteSpace(loggingEarly.FilePath))
{
    Console.WriteLine($"   ✓ File logging enabled → Would register FileLoggerService with path: {loggingEarly.FilePath}");

    //// Example: services.AddSingleton<IFileLogger>(new FileLogger(loggingEarly.FilePath));
}
else
{
    Console.WriteLine("   ✗ File logging disabled → Skipping FileLoggerService registration");
}

if (dbEarly.MaxRetries > 0)
{
    Console.WriteLine($"   ✓ Database retries enabled ({dbEarly.MaxRetries}) → Would register RetryPolicy service");

    //// Example: services.AddSingleton<IRetryPolicy>(new RetryPolicy(dbEarly.MaxRetries));
}

// Demonstrate Get vs GetOrAdd
Console.WriteLine("\n4. Get vs GetOrAdd (Understanding Caching Behavior):");
Console.WriteLine("   Three APIs available for early access to options:");
Console.WriteLine();

Console.WriteLine("   A) Get methods - Reads cache but doesn't populate:");
Console.WriteLine("      (Without GetOrAdd being called first)");
var dbGet1 = services.GetDatabaseOptionsFromOptionsBinding(configuration);
var dbGet2 = services.GetDatabaseOptionsFromOptionsBinding(configuration);
Console.WriteLine($"   ✓ First call: {dbGet1.ConnectionString[..Math.Min(30, dbGet1.ConnectionString.Length)]}...");
Console.WriteLine($"   ✓ Second call: {dbGet2.ConnectionString[..Math.Min(30, dbGet2.ConnectionString.Length)]}...");
Console.WriteLine($"   ✓ Same instance? {ReferenceEquals(dbGet1, dbGet2)} (no cache, creates fresh instances)");
Console.WriteLine();

Console.WriteLine("   B) GetOrAdd methods - Reads AND populates cache:");
var apiCached1 = services.GetOrAddApiOptionsFromOptionsBinding(configuration);
var apiCached2 = services.GetOrAddApiOptionsFromOptionsBinding(configuration);
Console.WriteLine($"   ✓ First call: {apiCached1.BaseUrl}");
Console.WriteLine($"   ✓ Second call: {apiCached2.BaseUrl}");
Console.WriteLine($"   ✓ Same instance? {ReferenceEquals(apiCached1, apiCached2)} (cached and reused)");
Console.WriteLine();

Console.WriteLine("   C) Get AFTER GetOrAdd - Benefits from cache:");
var apiFromGet = services.GetApiOptionsFromOptionsBinding(configuration);
Console.WriteLine($"   ✓ Get called after GetOrAdd: {apiFromGet.BaseUrl}");
Console.WriteLine($"   ✓ Same as cached? {ReferenceEquals(apiFromGet, apiCached1)} (Get found it in cache!)");
Console.WriteLine();

Console.WriteLine("   D) Smart Dispatcher GetOptions<T>() - Uses Get internally:");
var apiDispatch = services.GetOptions<ApiOptions>(configuration);
Console.WriteLine($"   ✓ GetOptions<ApiOptions>() → GetApiOptionsFromOptionsBinding()");
Console.WriteLine($"   ✓ Retrieved: {apiDispatch.BaseUrl}");
Console.WriteLine($"   ✓ Same as cached? {ReferenceEquals(apiDispatch, apiCached1)} (also benefits from cache!)");
Console.WriteLine();

Console.WriteLine("   Summary:");
Console.WriteLine("   - Get: Reads cache (efficient), doesn't populate (no side effects)");
Console.WriteLine("   - GetOrAdd: Reads AND populates cache (use for idempotency)");
Console.WriteLine("   - GetOptions<T>: Convenient generic API, same behavior as Get");

Console.WriteLine("\n=== Early Access Complete! Now building ServiceProvider for normal usage ===\n");

// Build service provider
var serviceProvider = services.BuildServiceProvider();

Console.WriteLine("1. Testing DatabaseOptions (with validation):");
Console.WriteLine("   - Section: \"Database\"");
Console.WriteLine("   - Validation: DataAnnotations + ValidateOnStart + ErrorOnMissingKeys");

try
{
    var dbOptions = serviceProvider.GetRequiredService<IOptions<DatabaseOptions>>();
    var db = dbOptions.Value;

    Console.WriteLine($"   ✓ ConnectionString: {db.ConnectionString}");
    Console.WriteLine($"   ✓ MaxRetries: {db.MaxRetries}");
    Console.WriteLine($"   ✓ TimeoutSeconds: {db.TimeoutSeconds}");
}
catch (OptionsValidationException ex)
{
    Console.WriteLine($"   ✗ Validation failed: {ex.Message}");
}

Console.WriteLine("\n2. Testing ApiOptions (explicit section path):");
Console.WriteLine("   - Section: \"App:Api\"");

var apiOptions = serviceProvider.GetRequiredService<IOptions<ApiOptions>>();
var api = apiOptions.Value;

Console.WriteLine($"   ✓ BaseUrl: {api.BaseUrl}");
Console.WriteLine($"   ✓ ApiKey: {api.ApiKey}");
Console.WriteLine($"   ✓ TimeoutSeconds: {api.TimeoutSeconds}");

Console.WriteLine("\n3. Testing LoggingOptions (explicit section name):");
Console.WriteLine("   - Section: \"Logging\"");

var loggingOptions = serviceProvider.GetRequiredService<IOptions<LoggingOptions>>();
var logging = loggingOptions.Value;

Console.WriteLine($"   ✓ Level: {logging.Level}");
Console.WriteLine($"   ✓ EnableConsole: {logging.EnableConsole}");
Console.WriteLine($"   ✓ EnableFile: {logging.EnableFile}");
Console.WriteLine($"   ✓ FilePath: {logging.FilePath ?? "(not set)"}");

Console.WriteLine("\n4. Testing EmailOptions (Named Options + ConfigureAll):");
Console.WriteLine("   - Named instances: \"Primary\", \"Secondary\", \"Fallback\"");
Console.WriteLine("   - Demonstrates multiple configurations of the same options type");
Console.WriteLine("   - Demonstrates ConfigureAll setting defaults for ALL named instances");

var emailSnapshot = serviceProvider.GetRequiredService<IOptionsSnapshot<Atc.SourceGenerators.OptionsBinding.Options.EmailOptions>>();

Console.WriteLine("\n   Primary Email Server:");
var primaryEmail = emailSnapshot.Get("Primary");
Console.WriteLine($"   ✓ SmtpServer: {primaryEmail.SmtpServer}");
Console.WriteLine($"   ✓ Port: {primaryEmail.Port}");
Console.WriteLine($"   ✓ FromAddress: {primaryEmail.FromAddress}");
Console.WriteLine($"   ✓ UseSsl: {primaryEmail.UseSsl}");
Console.WriteLine($"   ✓ TimeoutSeconds: {primaryEmail.TimeoutSeconds}");
Console.WriteLine($"   ✓ MaxRetries: {primaryEmail.MaxRetries} (set by ConfigureAll)");

Console.WriteLine("\n   Secondary Email Server:");
var secondaryEmail = emailSnapshot.Get("Secondary");
Console.WriteLine($"   ✓ SmtpServer: {secondaryEmail.SmtpServer}");
Console.WriteLine($"   ✓ Port: {secondaryEmail.Port}");
Console.WriteLine($"   ✓ FromAddress: {secondaryEmail.FromAddress}");
Console.WriteLine($"   ✓ MaxRetries: {secondaryEmail.MaxRetries} (set by ConfigureAll)");

Console.WriteLine("\n   Fallback Email Server:");
var fallbackEmail = emailSnapshot.Get("Fallback");
Console.WriteLine($"   ✓ SmtpServer: {fallbackEmail.SmtpServer}");
Console.WriteLine($"   ✓ Port: {fallbackEmail.Port}");
Console.WriteLine($"   ✓ FromAddress: {fallbackEmail.FromAddress}");
Console.WriteLine($"   ✓ UseSsl: {fallbackEmail.UseSsl}");
Console.WriteLine($"   ✓ MaxRetries: {fallbackEmail.MaxRetries} (set by ConfigureAll)");

Console.WriteLine("\n   → ConfigureAll set MaxRetries=3 for all instances (not in appsettings.json)!");

Console.WriteLine("\n5. Testing CloudStorageOptions (Nested Subsection Binding):");
Console.WriteLine("   - Section: \"CloudStorage\"");
Console.WriteLine("   - Demonstrates automatic binding of nested configuration subsections");

var cloudStorageOptions = serviceProvider.GetRequiredService<IOptions<CloudStorageOptions>>();
var cloudStorage = cloudStorageOptions.Value;

Console.WriteLine($"   ✓ Provider: {cloudStorage.Provider}");
Console.WriteLine($"   ✓ Azure.ConnectionString: {cloudStorage.Azure.ConnectionString[..Math.Min(40, cloudStorage.Azure.ConnectionString.Length)]}...");
Console.WriteLine($"   ✓ Azure.ContainerName: {cloudStorage.Azure.ContainerName}");
Console.WriteLine($"   ✓ Azure.Blob.MaxBlockSize: {cloudStorage.Azure.Blob.MaxBlockSize}");
Console.WriteLine($"   ✓ RetryPolicy.MaxRetries: {cloudStorage.RetryPolicy.MaxRetries}");

Console.WriteLine("\n6. Testing StoragePathsOptions (PostConfigure Feature):");
Console.WriteLine("   - Section: \"StoragePaths\"");
Console.WriteLine("   - Demonstrates PostConfigure for normalizing paths after binding");
Console.WriteLine("   - All paths are automatically normalized to end with directory separator");

var storagePathsOptions = serviceProvider.GetRequiredService<IOptions<StoragePathsOptions>>();
var storagePaths = storagePathsOptions.Value;

Console.WriteLine("\n   Original values from appsettings.json:");
Console.WriteLine("   - BasePath: \"C:\\\\Data\\\\Storage\" (no trailing separator)");
Console.WriteLine("   - CachePath: \"/var/cache/myapp\" (no trailing separator)");
Console.WriteLine("   - TempPath: \"C:\\\\Temp\\\\MyApp\" (no trailing separator)");
Console.WriteLine("   - LogPath: \"/var/log/myapp\" (no trailing separator)");

Console.WriteLine("\n   After PostConfigure normalization:");
Console.WriteLine($"   ✓ BasePath: \"{storagePaths.BasePath}\" (now ends with '{Path.DirectorySeparatorChar}')");
Console.WriteLine($"   ✓ CachePath: \"{storagePaths.CachePath}\"");
Console.WriteLine($"   ✓ TempPath: \"{storagePaths.TempPath}\"");
Console.WriteLine($"   ✓ LogPath: \"{storagePaths.LogPath}\"");
Console.WriteLine("   → PostConfigure automatically ensures consistent path formatting!");

Console.WriteLine("\n--- Domain Project Options ---\n");

Console.WriteLine("7. Testing CacheOptions (from Domain project):");
Console.WriteLine("   - Section: \"CacheOptions\" (auto-inferred, full class name)");

var cacheOptions = serviceProvider.GetRequiredService<IOptions<CacheOptions>>();
var cache = cacheOptions.Value;

Console.WriteLine($"   ✓ MaxSize: {cache.MaxSize}");
Console.WriteLine($"   ✓ DefaultExpirationSeconds: {cache.DefaultExpirationSeconds}");
Console.WriteLine($"   ✓ EnableDistributedCache: {cache.EnableDistributedCache}");

Console.WriteLine("\n8. Testing FeatureOptions (from Domain project):");
Console.WriteLine("   - Section: \"Features\"");
Console.WriteLine("   - Lifetime: Monitor (use IOptionsMonitor<T>)");

var featureOptions = serviceProvider.GetRequiredService<IOptionsMonitor<FeatureOptions>>();
var features = featureOptions.CurrentValue;

Console.WriteLine($"   ✓ EnableNewDashboard: {features.EnableNewDashboard}");
Console.WriteLine($"   ✓ EnableBetaFeatures: {features.EnableBetaFeatures}");
Console.WriteLine($"   ✓ EnableAdvancedSearch: {features.EnableAdvancedSearch}");
Console.WriteLine($"   ✓ MaxSearchResults: {features.MaxSearchResults}");

Console.WriteLine("\n=== Multi-Project Setup Demonstrated! ===");
Console.WriteLine("✓ Main project options registered via AddOptionsFromOptionsBinding");
Console.WriteLine("✓ Domain project options registered via AddOptionsFromDomain");
Console.WriteLine("\n=== All tests completed successfully! ===");