Console.WriteLine("=== Atc.SourceGenerators - Options Binding Sample ===\n");

// Build configuration
var configuration = new ConfigurationBuilder()
    .SetBasePath(Directory.GetCurrentDirectory())
    .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
    .Build();

// Create service collection
var services = new ServiceCollection();

// Register all options decorated with [OptionsBinding] attribute from both assemblies
// These extension methods are generated by the source generator
services.AddOptionsFromOptionsBinding(configuration);
services.AddOptionsFromDomain(configuration);

// Build service provider
var serviceProvider = services.BuildServiceProvider();

Console.WriteLine("1. Testing DatabaseOptions (with validation):");
Console.WriteLine("   - Section: \"Database\"");
Console.WriteLine("   - Validation: DataAnnotations + ValidateOnStart + ErrorOnMissingKeys");

try
{
    var dbOptions = serviceProvider.GetRequiredService<IOptions<DatabaseOptions>>();
    var db = dbOptions.Value;

    Console.WriteLine($"   ✓ ConnectionString: {db.ConnectionString}");
    Console.WriteLine($"   ✓ MaxRetries: {db.MaxRetries}");
    Console.WriteLine($"   ✓ TimeoutSeconds: {db.TimeoutSeconds}");
}
catch (OptionsValidationException ex)
{
    Console.WriteLine($"   ✗ Validation failed: {ex.Message}");
}

Console.WriteLine("\n2. Testing ApiOptions (explicit section path):");
Console.WriteLine("   - Section: \"App:Api\"");

var apiOptions = serviceProvider.GetRequiredService<IOptions<ApiOptions>>();
var api = apiOptions.Value;

Console.WriteLine($"   ✓ BaseUrl: {api.BaseUrl}");
Console.WriteLine($"   ✓ ApiKey: {api.ApiKey}");
Console.WriteLine($"   ✓ TimeoutSeconds: {api.TimeoutSeconds}");

Console.WriteLine("\n3. Testing LoggingOptions (explicit section name):");
Console.WriteLine("   - Section: \"Logging\"");

var loggingOptions = serviceProvider.GetRequiredService<IOptions<LoggingOptions>>();
var logging = loggingOptions.Value;

Console.WriteLine($"   ✓ Level: {logging.Level}");
Console.WriteLine($"   ✓ EnableConsole: {logging.EnableConsole}");
Console.WriteLine($"   ✓ EnableFile: {logging.EnableFile}");
Console.WriteLine($"   ✓ FilePath: {logging.FilePath ?? "(not set)"}");

Console.WriteLine("\n4. Testing EmailOptions (Named Options - Multiple Instances):");
Console.WriteLine("   - Named instances: \"Primary\", \"Secondary\", \"Fallback\"");
Console.WriteLine("   - Demonstrates multiple configurations of the same options type");

var emailSnapshot = serviceProvider.GetRequiredService<IOptionsSnapshot<Atc.SourceGenerators.OptionsBinding.Options.EmailOptions>>();

Console.WriteLine("\n   Primary Email Server:");
var primaryEmail = emailSnapshot.Get("Primary");
Console.WriteLine($"   ✓ SmtpServer: {primaryEmail.SmtpServer}");
Console.WriteLine($"   ✓ Port: {primaryEmail.Port}");
Console.WriteLine($"   ✓ FromAddress: {primaryEmail.FromAddress}");
Console.WriteLine($"   ✓ UseSsl: {primaryEmail.UseSsl}");
Console.WriteLine($"   ✓ TimeoutSeconds: {primaryEmail.TimeoutSeconds}");

Console.WriteLine("\n   Secondary Email Server:");
var secondaryEmail = emailSnapshot.Get("Secondary");
Console.WriteLine($"   ✓ SmtpServer: {secondaryEmail.SmtpServer}");
Console.WriteLine($"   ✓ Port: {secondaryEmail.Port}");
Console.WriteLine($"   ✓ FromAddress: {secondaryEmail.FromAddress}");

Console.WriteLine("\n   Fallback Email Server:");
var fallbackEmail = emailSnapshot.Get("Fallback");
Console.WriteLine($"   ✓ SmtpServer: {fallbackEmail.SmtpServer}");
Console.WriteLine($"   ✓ Port: {fallbackEmail.Port}");
Console.WriteLine($"   ✓ FromAddress: {fallbackEmail.FromAddress}");
Console.WriteLine($"   ✓ UseSsl: {fallbackEmail.UseSsl}");

Console.WriteLine("\n--- Domain Project Options ---\n");

Console.WriteLine("5. Testing CacheOptions (from Domain project):");
Console.WriteLine("   - Section: \"CacheOptions\" (auto-inferred, full class name)");

var cacheOptions = serviceProvider.GetRequiredService<IOptions<CacheOptions>>();
var cache = cacheOptions.Value;

Console.WriteLine($"   ✓ MaxSize: {cache.MaxSize}");
Console.WriteLine($"   ✓ DefaultExpirationSeconds: {cache.DefaultExpirationSeconds}");
Console.WriteLine($"   ✓ EnableDistributedCache: {cache.EnableDistributedCache}");

Console.WriteLine("\n6. Testing FeatureOptions (from Domain project):");
Console.WriteLine("   - Section: \"Features\"");
Console.WriteLine("   - Lifetime: Monitor (use IOptionsMonitor<T>)");

var featureOptions = serviceProvider.GetRequiredService<IOptionsMonitor<FeatureOptions>>();
var features = featureOptions.CurrentValue;

Console.WriteLine($"   ✓ EnableNewDashboard: {features.EnableNewDashboard}");
Console.WriteLine($"   ✓ EnableBetaFeatures: {features.EnableBetaFeatures}");
Console.WriteLine($"   ✓ EnableAdvancedSearch: {features.EnableAdvancedSearch}");
Console.WriteLine($"   ✓ MaxSearchResults: {features.MaxSearchResults}");

Console.WriteLine("\n=== Multi-Project Setup Demonstrated! ===");
Console.WriteLine("✓ Main project options registered via AddOptionsFromOptionsBinding");
Console.WriteLine("✓ Domain project options registered via AddOptionsFromDomain");
Console.WriteLine("\n=== All tests completed successfully! ===");