// =============================================================================
// Configuration-Based Mapping Demo
// Maps third-party CRM SDK types to domain models WITHOUT attributes on source types.
// =============================================================================

Console.WriteLine("=== Configuration-Based Mapping Demo ===");
Console.WriteLine();

// Simulate receiving data from a CRM SDK
var crmContact = new Contact
{
    ContactId = 42,
    FullName = "Jane Smith",
    EmailAddress = "jane.smith@example.com",
    PhoneNumber = "+1-555-0123",
    Type = ContactType.Company,
    CreatedDate = new DateTime(2024, 1, 15, 10, 30, 0, DateTimeKind.Utc),
    ModifiedDate = new DateTime(2024, 6, 20, 14, 45, 0, DateTimeKind.Utc),
    InternalTrackingCode = "CRM-INTERNAL-12345",
    PrimaryAddress = new ContactAddress
    {
        Street = "123 Business Ave",
        City = "Seattle",
        State = "WA",
        ZipCode = "98101",
        Country = "US",
    },
};

Console.WriteLine("--- Source: CRM Contact ---");
Console.WriteLine($"  ContactId: {crmContact.ContactId}");
Console.WriteLine($"  FullName: {crmContact.FullName}");
Console.WriteLine($"  EmailAddress: {crmContact.EmailAddress}");
Console.WriteLine($"  PhoneNumber: {crmContact.PhoneNumber}");
Console.WriteLine($"  Type: {crmContact.Type}");
Console.WriteLine($"  CreatedDate: {crmContact.CreatedDate}");
Console.WriteLine($"  ModifiedDate: {crmContact.ModifiedDate}");
Console.WriteLine($"  InternalTrackingCode: {crmContact.InternalTrackingCode}");
Console.WriteLine($"  PrimaryAddress.ZipCode: {crmContact.PrimaryAddress?.ZipCode}");
Console.WriteLine();

// Map using the configuration-based mapping (generated by MappingConfigurationGenerator)
var customer = crmContact.MapToCustomer();

Console.WriteLine("--- Target: Domain Customer ---");
Console.WriteLine($"  Id: {customer.Id}");
Console.WriteLine($"  Name: {customer.Name}");
Console.WriteLine($"  Email: {customer.Email}");
Console.WriteLine($"  Phone: {customer.Phone}");
Console.WriteLine($"  Category: {customer.Category}");
Console.WriteLine($"  CreatedAt: {customer.CreatedAt}");
Console.WriteLine($"  UpdatedAt: {customer.UpdatedAt}");
Console.WriteLine($"  Address.PostalCode: {customer.Address?.PostalCode}");
Console.WriteLine();

Console.WriteLine("--- Feature Highlights ---");
Console.WriteLine($"  Property renamed: FullName -> Name = '{customer.Name}'");
Console.WriteLine($"  Property renamed: EmailAddress -> Email = '{customer.Email}'");
Console.WriteLine($"  Property renamed: ZipCode -> PostalCode = '{customer.Address?.PostalCode}'");
Console.WriteLine($"  Property ignored: ContactId (not mapped)");
Console.WriteLine($"  Property ignored: InternalTrackingCode (not mapped)");
Console.WriteLine($"  Enum auto-detected: ContactType.{crmContact.Type} -> CustomerCategory.{customer.Category}");
Console.WriteLine($"  Nested mapping: ContactAddress -> Address (via CrmMappings.MapToAddress)");

Console.WriteLine();
Console.WriteLine("=== Demo Complete ===");